### PR TITLE
Updated Razorpay Framework to 1.1.0

### PR DESCRIPTION
**Pull request by koushikmln**
Updated Razorpay Framework to 1.1.0. Existing version is not working with xcode 10.2

### CODE REVIEW

**Comment by essuraj** [comment]
When will this be merged @iThink32 . having issues on xcode 10.2

**Comment by AbhinavArora95** [comment]
Thank you for your contribution. But unfortunately as we can't review a binary change (framework change), I'll not be merging the PR and will be closing it. Still, thank you for your efforts.

**Comment by koushikmln** [comment]
Let me know when the library will be updated. Im forced to use a local fork due to the compilation issues. I just made the PR to get it to your attention and for people who needed some alternative.

**Comment by AbhinavArora95** [comment]
@koushikmln Just updated the framework. It has been merged in the master.

**Comment by koushikmln** [comment]
Thanks

**Pull request closed without merging**
